f=open("sample.txt",'w')
f.write("\n helo darknesssmy old friend \n ive come to talk with you again")
f.close()
f=open("sample.txt",'r+')
f.seek(0,1)
f.write("\n helo darknesssmy old friend \n ive come to talk with you again")
f.seek(0,0)
c=f.read()
print(c[::-1])
print(f.read())
print(c)
